### ISSUE TITLE
AttributeError: module 'boozelib' has no attribute 'get_blood_alcohol_degradation'

### ISSUE THREAD

**Issue by nikhilmaddirala** [brutus/boozelib#3]
See details here: https://gist.github.com/nikhilmaddirala/f28b81b4ac829e8b7f5d515368fd4897

**Comment by nikhilmaddirala** [comment]
Created a PR to fix this problem: https://github.com/brutus/boozelib/pull/4

**Comment by brutus** [comment]
Hi @nikhilmaddirala thanks for the report and PR.

This repo's _main_ branch was in a state between two releases `0.5` and `0.6`. The README (and the docs) where already using the new function names and signatures, while PyPI still delivered `0.5`.

This should be fixed, since `0.6` is now here on Github, as well as on [PyPI](https://pypi.org/project/boozelib/) and the [docs](https://boozelib.readthedocs.org/). Hope this fixes the issue for you too. You can find a writeup of the biggest changes in [the change log](https://github.com/brutus/boozelib/blob/master/CHANGELOG.md#060-2021-02-02).
